# 简介
部分功能模块并不支持协程，它们只提供了接口回调风格的API，如果我们直接在协程代码中调用这些接口，就会增加嵌套层级、降低代码的可维护性。

Kotlin协程库提供了 `suspendCoroutine()` 等工具，用于将接口回调风格的API转换为挂起函数，以便在协程代码中调用，减少嵌套层级并统一编码风格。

🔴 示例一

在本示例中，我们定义一个接口回调风格的模拟网络请求API，并演示它的调用方法。

第一步，我们定义回调接口，并在模拟网络请求的方法中调用它的实现。

"TestWorkWithThread.kt":

```kotlin
// 网络请求回调接口
interface NetCallback {

    // 请求成功
    fun onSuccess(data: String)

    // 请求失败
    fun onFailure(message: String)
}

/**
 * 模拟网络请求。
 *
 * @param[result] 控制请求结果。
 * @param[callback] 结果回调。
 */
fun request(result: Boolean, callback: NetCallback) {
    // 开启新线程进行网络请求
    thread {
        // 线程休眠，模拟网络延时。
        Thread.sleep(3000L)
        // 休眠结束，调用回调方法反馈执行结果。
        if (result) {
            callback.onSuccess("200 - OK.")
        } else {
            callback.onFailure("502 - Bad Gateway.")
        }
    }
}
```

NetCallback接口定义了两个方法，其中 `onSuccess()` 方法在请求成功时被触发，参数为服务端返回的数据； `onFailure()` 方法则在请求失败时被触发，参数为错误信息。

`request()` 方法用于模拟网络请求，其中开启了一个线程，休眠3秒以模拟网络耗时，休眠结束后根据参数 `result` 调用NetCallback实例的对应方法，向调用者反馈请求结果。

第二步，调用者使用该接口时，需要传入NetCallback实现类的实例，并在结果返回时执行对应的操作（例如更新界面），此处我们只是简单的将回调结果输出到控制台上。

"TestWorkWithThread.kt":

```kotlin
println("Mock request start. Time:[${getTime()}]")
request(true, object : NetCallback {
    override fun onSuccess(data: String) {
        println("OnSuccess. Time:[${getTime()}] Data:[$data]")
    }

    override fun onFailure(message: String) {
        println("OnFailure. Time:[${getTime()}] Info:[$message]")
    }
})
```

此时运行示例程序，并查看控制台输出信息：

```text
Mock request start. Time:[23:18:09.453]
OnSuccess. Time:[23:18:12.481] Data:[200 - OK.]
```

根据上述输出内容可知：

`request()` 方法被调用3秒后，NetCallback实例的 `onSuccess()` 回调方法被触发，输出了请求结果。

# "suspendCoroutine()"方法
## 基本应用
`suspendCoroutine()` 方法是一种允许开发者控制协程任务暂停与恢复的工具，我们可以用它将前文“示例一”中的回调风格接口 `request()` 转换为挂起函数。

🟠 示例二

在本示例中，我们使用 `suspendCoroutine()` 方法将回调接口 `request()` 转换为挂起函数。

第一步，我们定义 `requestSuspend()` 方法实现转换逻辑。

"TestWorkWithThread.kt":

```kotlin
// 模拟网络请求（挂起函数实现）。
private suspend fun requestSuspend(result: Boolean): String {
    return suspendCoroutine {
        request(result, object : NetCallback {
            override fun onSuccess(data: String) {
                // 请求成功，解除挂起状态并返回数据。
                it.resume(data)
            }

            override fun onFailure(message: String) {
                // 请求失败，抛出异常。
                val exception = Exception(message)
                it.resumeWithException(exception)
            }
        })
    }
}
```

当协程任务运行至 `suspendCoroutine()` 方法时，进入暂停状态，随后调度器开始执行模拟网络请求。当回调方法 `onSuccess()` 通知请求成功事件时，我们需要调用 `it.resume()` 方法通知协程任务从暂停状态恢复，并传入参数来传递回调方法的请求结果。 `suspendCoroutine()` 方法的返回值是一个泛型类型，与 `it.resume()` 方法的参数类型保持一致，此处请求结果 `data` 的数据类型为String，因此 `suspendCoroutine()` 方法的返回值类型也是String。

第二步，我们在协程任务中调用 `requestSuspend()` 挂起函数，以协程的方式使用模拟网络请求API。

"TestWorkWithThread.kt":

```kotlin
CoroutineScope(Dispatchers.IO).launch {
    println("Mock request start. Time:[${getTime()}]")
    // 声明变量以便接收请求成功的结果
    val data = requestSuspend(true)
    println("Request success. Time:[${getTime()}] Data:[$data]")
}
```

此时运行示例程序，并查看控制台输出信息：

```text
Mock request start. Time:[21:18:09.453]
Request success. Time:[21:18:12.481] Data:[200 - OK.]
```

根据上述输出内容可知：

协程任务运行至 `suspendCoroutine()` 方法时，进入暂停状态，调度器开始执行模拟网络请求；3秒后，回调接口触发了 `onSuccess()` 回调方法及其中的 `it.resume()` 方法，调用者接收到请求结果并从暂停状态恢复。

下文列表展示了 `suspendCoroutine()` 方法的一些特性：

- `it.resume()` 语句只能被调用一次，否则会导致异常： `IllegalStateException: Already resumed` 。
- 如果 `it.resume()` 语句之后还有其他语句，当 `it.resume()` 语句被调用后，剩余的语句仍然会被执行。

## 反馈异常状态
NetCallback接口有“请求成功”和“请求失败”两种情况，由于挂起函数只能有单个返回值，已经被我们用来反馈成功状态，因此我们需要通过异常机制反馈失败状态给调用者。

🟡 示例三

在本示例中，我们通过捕获 `requestSuspend()` 方法可能发生的异常，处理请求失败事件。

在前文“示例二”中，我们已经在模拟网络请求回调失败结果时，调用 `it.resumeWithException()` 语句向调用者抛出异常，因此只需要在调用 `requestSuspend()` 方法的协程体中添加"try ... catch"语句即可。

"TestWorkWithThread.kt":

```kotlin
CoroutineScope(Dispatchers.IO).launch {
    try {
        println("Mock request start. Time:[${getTime()}]")
        // 模拟请求失败的情况
        val data = requestSuspend(false)
        println("Request success. Time:[${getTime()}] Data:[$data]")
    } catch (e: Exception) {
        // 捕获异常以获取失败详情
        println("Request failure. Info:[${e.message}]")
    }
}
```

此时运行示例程序，并查看控制台输出信息：

```text
Mock request start. Time:[21:22:02.464]
Request failure. Time:[21:22:05.580] Info:[502 - Bad Gateway.]
```

根据上述输出内容可知：

模拟网络请求开始3秒后，触发了 `onFailure()` 回调方法及其中的 `it.resumeWithException()` 方法，向调用者抛出异常信息；随后调用 `requestSuspend()` 方法的协程体捕获了异常信息，并且通过Exception实例获取异常详情。

## 处理中断请求
在前文“示例二”中，通过 `suspendCoroutine()` 方法构建的挂起函数并不支持中断请求，外部调用 `cancel()` 方法不会有任何反应，协程任务会继续执行直到任务完成为止。

为了支持响应中断任务的请求，我们可以将 `suspendCoroutine()` 方法替换为 `suspendCancellableCoroutine()` 方法，它们的使用方法完全相同，后者额外增加了中断处理功能。

🟢 示例四

在本示例中，我们为前文“示例二”中的 `requestSuspend()` 方法添加中断处理功能。

第一步，我们定义 `requestSuspend2()` 方法。

"TestWorkWithThread.kt":

```kotlin
private suspend fun requestSuspend2(result: Boolean): String {
    return suspendCancellableCoroutine {
        // 此处可以书写收到中断请求后的清理工作
        it.invokeOnCancellation {
            println("Task was canceled!")
        }

        request(result, object : NetCallback {
            override fun onSuccess(data: String) {
                // 请求成功，解除挂起状态并返回数据。
                it.resume(data)
            }

            override fun onFailure(message: String) {
                // 请求失败，抛出异常。
                val exception = Exception(message)
                it.resumeWithException(exception)
            }
        })
    }
}
```

此处我们使用 `it.invokeOnCancellation()` 方法注册了一个回调方法，其中的代码将在收到中断请求后被执行，通常用来进行释放资源、清理临时文件等善后操作。

第二步，我们创建一个协程任务调用挂起函数 `requestSuspend2()` ，并在主线程中发起中断请求。

"TestWorkWithThread.kt":

```kotlin
val job: Job = CoroutineScope(Dispatchers.IO).launch {
    try {
        println("Mock request start. Time:[${getTime()}]")
        // 模拟请求失败的情况
        val data = requestSuspend2(true)
        println("Request success. Time:[${getTime()}] Data:[$data]")
    } catch (e: Exception) {
        // 捕获异常以获取失败详情
        println("Request failure. Time:[${getTime()}] Info:[${e.message}]")
    }
}

// 延时1秒后取消协程任务
Thread.sleep(1000L)
job.cancel(CancellationException("Task has been canceled."))
```

此时运行示例程序，并查看控制台输出信息：

```text
Mock request start. Time:[16:20:37.158]
Task was canceled!
Request failure. Time:[16:20:38.149] Info:[Task has been canceled.]
```

# "runBlocking()"方法
`runBlocking()` 方法的功能与CoroutineScope的 `launch()` 和 `async()` 方法类似，都可以提供协程环境并开启协程任务，但 `launch()` 和 `async()` 方法属于CoroutineScope实例，且不会阻塞调用者线程； `runBlocking()` 方法则可以被直接调用，不需要依赖CoroutineScope实例，并且会阻塞调用者线程，直到协程任务运行完毕。

该方法的主要用途是将协程API转换为接口回调API，以便调用者在不支持协程的环境中使用这些API；除此之外，该方法还可以用于在 `main()` 方法中测试协程API。

🔵 示例五

在本示例中，我们使用 `runBlocking()` 方法将前文“示例二”中的挂起函数 `requestSuspend()` 转换为接口回调形式。

第一步，我们定义 `requestCallback()` 方法实现转换逻辑。

"TestWorkWithThread.kt":

```kotlin
// 模拟网络请求（协程转接口回调）。
fun requestCallback(result: Boolean, callback: NetCallback) {
    // 在新线程进行网络请求
    thread {
        // 开启协程任务并阻塞当前线程
        runBlocking {
            try {
                val data: String = requestSuspend(result)
                // 获取到结果后，通过回调方法通知调用者。
                callback.onSuccess(data)
            } catch (e: Exception) {
                callback.onFailure(e.message ?: "")
            }
        }
    }
}
```

第二步，我们在测试代码中调用该方法。

"TestWorkWithThread.kt":

```kotlin
println("Mock request start. Time:[${getTime()}]")
requestCallback(true, object : NetCallback {
    override fun onSuccess(data: String) {
        println("OnSuccess. Time:[${getTime()}] Data:[$data]")
    }

    override fun onFailure(message: String) {
        println("OnFailure. Time:[${getTime()}] Info:[$message]")
    }
})
```

此时运行示例程序，并查看控制台输出信息：

```text
Mock request start. Time:[14:36:08.621]
OnSuccess. Time:[14:36:11.672] Data:[200 - OK.]
```

🟣 示例六

在本示例中，我们使用 `runBlocking()` 方法编写协程的测试代码。

"TestCooperation.kt":

```kotlin
fun main() {
    runBlocking {
        // 启动协程后调用"join()"方法，使主线程等待协程执行完毕。
        CoroutineScope(Dispatchers.Default).launch {
            println("Task start.")
            delay(2000)
            println("Task end.")
        }.join()
    }
println("Main thread end.")
}
```

上述代码是用于测试协程的常用写法，我们首先使用 `runBlocking()` 创建协程环境并阻塞主线程，然后运行待测试的协程任务，并调用它的 `join()` 方法，使 `runBlocking()` 所创建的协程等待待测试的执行完毕。

此时运行示例程序，并查看控制台输出信息：

```text
Task start.
Task end.
Main thread end.
```

这种方式相比前文示例中调用 `Thread.sleep()` 阻塞主线程更为灵活，因为待测试的协程任务运行时长可能是随机的，此时我们无法得知 `Thread.sleep()` 的参数。
